#pragma once

#define FOREGROUND_BLACK 0x00
#define FOREGROUND_BLUE 0x01
#define FOREGROUND_GREEN 0x02
#define FOREGROUND_CYAN 0x03
#define FOREGROUND_RED 0x04
#define FOREGROUND_MAGENTA 0x05
#define FOREGROUND_BROWN 0x06
#define FOREGROUND_LGRAY 0x07
#define FOREGROUND_DGRAY 0x08
#define FOREGROUND_LBLUE 0x09
#define FOREGROUND_LGREEN 0x0A
#define FOREGROUND_LCYAN 0x0B
#define FOREGROUND_LRED 0x0C
#define FOREGROUND_LMAGENTA 0x0D
#define FOREGROUND_YELLOW 0x0E
#define FOREGROUND_WHITE 0x0F

#define BACKGROUND_BLACK 0x00
#define BACKGROUND_BLUE 0x10
#define BACKGROUND_GREEN 0x20
#define BACKGROUND_CYAN  0x30
#define BACKGROUND_RED 0x40
#define BACKGROUND_MAGENTA 0x50
#define BACKGROUND_BROWN 0x60
#define BACKGROUND_LGRAY 0x70

//If using these colors, the text printed on these will be flashing
#define BG_BLINKINGBLACK 0x80
#define BG_BLINKINGBLUE 0x90
#define BG_BLINKINGGREEN 0xA0
#define BG_BLINKINGCYAN 0xB0
#define BG_BLINKINGRED 0xC0
#define BG_BLINKINGMAGENTA 0xD0
#define BG_BLINKINGYELLOW 0xE0
#define BG_BLINKINGWHITE 0xF0